name: Git Actions Test Automation
on:
  push: 
    branches: [main]
jobs:
  test-job:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Initialise Node
        uses: actions/setup-node@v4

      - name: Install Node
        run: npm ci

      - name: Test Backend
        run: npm test

      
